// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;

namespace Myelin.Core.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "myelin_ffi";

        [DllImport(__DllName, EntryPoint = "myelin_workspace_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern WorkspaceHandle* myelin_workspace_create(byte* root_path);

        [DllImport(__DllName, EntryPoint = "myelin_workspace_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void myelin_workspace_destroy(WorkspaceHandle* handle);

        [DllImport(__DllName, EntryPoint = "myelin_workspace_open_scratch", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong myelin_workspace_open_scratch(WorkspaceHandle* handle, byte* initial_text);

        [DllImport(__DllName, EntryPoint = "myelin_workspace_open_file", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong myelin_workspace_open_file(WorkspaceHandle* handle, byte* path_utf8);

        [DllImport(__DllName, EntryPoint = "myelin_workspace_close_doc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_workspace_close_doc(WorkspaceHandle* handle, ulong doc_id);

        [DllImport(__DllName, EntryPoint = "myelin_doc_get_line_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint myelin_doc_get_line_count(WorkspaceHandle* handle, ulong doc_id);

        [DllImport(__DllName, EntryPoint = "myelin_doc_get_line", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* myelin_doc_get_line(WorkspaceHandle* handle, ulong doc_id, nuint line_idx);

        [DllImport(__DllName, EntryPoint = "myelin_doc_get_visible_lines_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* myelin_doc_get_visible_lines_json(WorkspaceHandle* handle, ulong doc_id, nuint start_line, nuint end_line);

        [DllImport(__DllName, EntryPoint = "myelin_doc_get_styled_lines_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* myelin_doc_get_styled_lines_json(WorkspaceHandle* handle, ulong doc_id, nuint start_line, nuint end_line);

        [DllImport(__DllName, EntryPoint = "myelin_doc_insert_at_cursor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_doc_insert_at_cursor(WorkspaceHandle* handle, ulong doc_id, byte* text_utf8);

        [DllImport(__DllName, EntryPoint = "myelin_doc_backspace", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_doc_backspace(WorkspaceHandle* handle, ulong doc_id);

        [DllImport(__DllName, EntryPoint = "myelin_doc_delete_forward", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_doc_delete_forward(WorkspaceHandle* handle, ulong doc_id);

        [DllImport(__DllName, EntryPoint = "myelin_doc_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong myelin_doc_version(WorkspaceHandle* handle, ulong doc_id);

        [DllImport(__DllName, EntryPoint = "myelin_doc_undo", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_doc_undo(WorkspaceHandle* handle, ulong doc_id);

        [DllImport(__DllName, EntryPoint = "myelin_doc_redo", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_doc_redo(WorkspaceHandle* handle, ulong doc_id);

        [DllImport(__DllName, EntryPoint = "myelin_doc_get_cursor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_doc_get_cursor(WorkspaceHandle* handle, ulong doc_id, nuint* out_line, nuint* out_col);

        [DllImport(__DllName, EntryPoint = "myelin_doc_set_cursor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_doc_set_cursor(WorkspaceHandle* handle, ulong doc_id, nuint line, nuint col);

        [DllImport(__DllName, EntryPoint = "myelin_doc_set_selection", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_doc_set_selection(WorkspaceHandle* handle, ulong doc_id, nuint anchor_line, nuint anchor_col, nuint head_line, nuint head_col);

        [DllImport(__DllName, EntryPoint = "myelin_doc_get_selection", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_doc_get_selection(WorkspaceHandle* handle, ulong doc_id, nuint* out_anchor_line, nuint* out_anchor_col, nuint* out_head_line, nuint* out_head_col);

        [DllImport(__DllName, EntryPoint = "myelin_doc_is_dirty", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_doc_is_dirty(WorkspaceHandle* handle, ulong doc_id);

        [DllImport(__DllName, EntryPoint = "myelin_doc_save", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_doc_save(WorkspaceHandle* handle, ulong doc_id);

        [DllImport(__DllName, EntryPoint = "myelin_workspace_scan_dir_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* myelin_workspace_scan_dir_json(byte* dir_path_utf8, nuint max_depth);

        [DllImport(__DllName, EntryPoint = "myelin_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void myelin_free_string(byte* ptr);

        [DllImport(__DllName, EntryPoint = "myelin_terminal_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern TerminalHandle* myelin_terminal_create(ushort cols, ushort rows, byte* working_dir);

        [DllImport(__DllName, EntryPoint = "myelin_terminal_create_profile", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern TerminalHandle* myelin_terminal_create_profile(ushort cols, ushort rows, byte* working_dir, byte* shell_path_utf8, byte* shell_args_utf8);

        [DllImport(__DllName, EntryPoint = "myelin_terminal_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void myelin_terminal_destroy(TerminalHandle* handle);

        [DllImport(__DllName, EntryPoint = "myelin_terminal_write", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_terminal_write(TerminalHandle* handle, byte* input_utf8);

        [DllImport(__DllName, EntryPoint = "myelin_terminal_read_available", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* myelin_terminal_read_available(TerminalHandle* handle);

        [DllImport(__DllName, EntryPoint = "myelin_terminal_read_raw", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* myelin_terminal_read_raw(TerminalHandle* handle);

        [DllImport(__DllName, EntryPoint = "myelin_terminal_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_terminal_resize(TerminalHandle* handle, ushort cols, ushort rows);

        [DllImport(__DllName, EntryPoint = "myelin_terminal_is_alive", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int myelin_terminal_is_alive(TerminalHandle* handle);
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct WorkspaceHandle
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TerminalHandle
    {
    }
}
